### ISSUE TITLE
2021-07-15 errorReport

### ISSUE THREAD

**Issue by Gyoung-min** [Gyoung-min/dailyStudy#73]
## DB 불러오기 에러

- 코드는 다음과 같다.

1. VO
```
package com.sboot.kaja.vo;

import lombok.Data;

@Data
public class SawonVO {
	private String name;
	private String tel;
}
```

2. DAO

```
package com.sboot.kaja.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.sboot.kaja.vo.SawonVO;

@Mapper //mapping를 위해 xml에서 정의한다
public interface SawonDAO {
	public List<SawonVO> getAllInfo();

}
```
3. controller

```
package com.sboot.kaja;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import com.sboot.kaja.dao.SawonDAO;
import com.sboot.kaja.vo.SawonVO;

@Controller

public class kajaController {
	
	@Autowired
	SawonDAO dao;

	@RequestMapping("/")
	public String kaja() {
		return "redirect:getallinfo";
	}
	
	@RequestMapping("/getallinfo")
	public String getallinfo(Model model) {
		model.addAttribute("getallinfo",dao.getAllInfo());
		
		System.out.println(dao.getAllInfo());
		return "getallinfo";
	}
	
}
```

4. JSP
```
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>

	<h1>사원 전체 보기</h1>
	<table border="2">
		<tr><th>이름</th><th>전화번호</th></tr>
		<c:forEach var="imsi" items="${getallinfo}">
			<tr>
				<th>${imsi.name}</th>
				<th>${imsi.tel}</th>
			</tr>
		</c:forEach>
	</table> <br />
	
	<a href="insertForm">[사원입력]</a>

</body>
</html>
```
5. mapper
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<!-- <mapper namespace="mapper.mybatismapper"> -->
<mapper namespace="com.sboot.kaja.dao.SawonDAO">

<select id="getAllInfo" resultType="com.sboot.kaja.vo.SawonVO">
	SELECT * FROM teltable333 order by name
</select>


</mapper>
```

## 문제 과정
- 기존 테이블과 신규 테이블 불러오는데에 차이가 있다.
- 다음 표에서 `TABLE333` 만 새로 만든 테이블이며 나머지 테이블은 예전에 만들었던 테이블들이다.
![테이블 표](https://user-images.githubusercontent.com/78856207/125731524-49e85a15-84b3-432d-8529-a6e2080012a7.PNG)

- 기존 테이블 불러오기에는 이상이 없다.
![기존](https://user-images.githubusercontent.com/78856207/125731747-24000774-5c58-45b7-97e6-8005e2c8fa2e.PNG)

`[SawonVO(name=babo, tel=010-777-8888), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=choonhayng3, tel=010-7777-5555), SawonVO(name=kongjoo, tel=010-8888-0000)]`

- 하지만 새로 만든 테이블에 내용은 받아오지 못하고 있다.
![새거](https://user-images.githubusercontent.com/78856207/125731914-40a64221-cc62-4ca3-a06e-9dbe0bc06724.PNG)

`[]`

- 다음과 같은 에러가 나타난다
![실패시 매시지](https://user-images.githubusercontent.com/78856207/125732439-01239c08-edb2-467d-a200-7ffa0de8f2e0.PNG)

- 신규 테이블의 선언은 다음과 같이 되어 있으며 `SELECT`를 통에 DB에는 저장이 되어 있음을 확인했다
![에러에러](https://user-images.githubusercontent.com/78856207/125732003-87d49cff-6089-4976-a4c7-b7cb1f827ea2.PNG)

**Comment by lette1394** [comment]
@Gyoung-min 
해결한 방법과 그 과정에서 알게된 내용 정리해주시고 close 부탁드립니다ㅎㅎ

**Comment by Gyoung-min** [comment]
DB commit을 생활화 합시다..
